### ISSUE TITLE
RCSB failed during structure build

### ISSUE THREAD

**Issue by pszgaspar** [protwis/protwis#256]
In contruct/functions.py the query to RCSB (`"https://www.rcsb.org/pdb/explore/jmol.do?structureId=$index&json=true"`) fails upon build. RCSB has updated the API so this query type has been deprecated and needs a new query with parsing the output. The issue relates to the `fetch_from_web_api` function in common/tools.py.

**Comment by AJK-dev** [comment]
Just archiving some wisdom van @cmunk regarding this issue:

> For these modifications, I "think" it doesn't have too many implications. It mainly captures disulfide bonds, which aren't that interesting or used in calculation. It's used to populate ConstructModification objects, but I'm actually not really seeing that used anyway if I search in the whole repo. If you wanted to go further into the rabbit hole, you could investigate a former build and check out the construct_modification table and see if it had anything of seeming interest. In my immediate memory and digging around the code indicates that it's not that crucial.

**Comment by AJK-dev** [comment]
And now also adding a few notes from a while ago when I was looking into this:

As far as I can see the RCSB changed the "protein modification annotations" and not all annotations from the _jmol.do_ interface can be found. Also in the new API (or for that matter also the old), I could not find any way of retrieving the protein modification annotations. Hopefully somebody has another experience and found a solution.
The only possibility I saw now, for the remaining protein modification annotations, is via crude parsing the _annotation_ HTML page of a structure: e.g. https://www.rcsb.org/Annotations/6PJX

That said, in combination with Christian his input + the fact that the annotation itself is currently not used anywhere, we might want to remove the code instead of creating an ugly workaround.

**Comment by pszgaspar** [comment]
rcsb.org changed their API, not relevant anymore
