### ISSUE TITLE
JS errors on Structure statistics page load

### ISSUE THREAD

**Issue by pszgaspar** [protwis/protwis#264]
Uncaught TypeError: $(...).catcomplete is not a function
and
Uncaught TypeError: $(...).submenupicker is not a function

**Comment by AJK-dev** [comment]
A very old jquery is being used for the graphs on these page (v1.11.1) and overrides the default jquery thereby breaking these functions. Since this is breaking especially the trees, the code needs to be updated to be able to work with our default jquery version. @Jimmy-A-Caroli since you will be working on the trees anyway, could you also look into this issue?

**Comment by AJK-dev** [comment]
@Jimmy-A-Caroli has updated structure_statistics html (https://github.com/protwis/protwis/commit/d7a4b6dbc1229dc6343adb8037db51184a4ae982) and together with the commit above (https://github.com/AJK-dev/protwis/commit/e694a7bc503ca431eb76529a9b363c49c2c648cc) this will close the issue.

The only problem was the way in which the window "load" function was called, rest of the code is backward compatible 🎉 
The old way:
`$(window).load(function() {});`

The new way:
`$(window).on("load",function() {});`

All in all, two old jquery libraries have been removed and (hopefully?) all affected related pages have been updated.
