### ISSUE TITLE
Not able to download CSV/SMILES of ligands 

### ISSUE THREAD

**Issue by Srilok** [protwis/protwis#432]
Hi, 

Thanks for the great contribution! 

I am not able to download the CSV or the SMILES of the ligands for any protein of interest from the GPCRdb. Clicking the download button on the top left does not do anything. I would highly appreciate any help with this 

Regards, 
Srilok

**Comment by pszgaspar** [comment]
Hi Srilok,

Thanks for raising the issue. We will be looking into this right away.

Best,
Gaspar

**Comment by sperezconesa** [comment]
Hello @pszgaspar , 
I had this problem until today, too. It seems like this problems is fixed, I am able to download csvs.

The problem I have now is in the select all check-box. When I hit select all, I just select the ligands in the current page displayed (the first 50 entries for examples). I think the expected behaviour would be that the 7000 ligands of my query were selected for download.

Thank you and keep up the great work!
Sergio

**Comment by sperezconesa** [comment]
I'm referreing to GPCRdb by the way.

**Comment by pszgaspar** [comment]
@sperezconesa we also closed issue #441 now to address your request. We added a "Select full table" button and renamed the checkbox.
