### ISSUE TITLE
Discrepancy between protein-ligand interactions on webpage and excel download

### ISSUE THREAD

**Issue by martinex** [protwis/protwis#57]
For example at http://gpcrdb.org/interaction/3OE6 only 5 interactions are shown in the table but 21 in the downloadable excel file. The difference comes from the accessible residues. The accessible residues are also not fetched through the API.

**Comment by AJK-dev** [comment]
Hi Márton, after a couple of years a comment ;-)
The accessible interactions are used to outline the pocket and to visualize the ligand in the pocket. Due to their lower value we chose to only list the explicit contacts in the table. However, the "accessible" interactions are now also accessible via the API.

**Comment by martinex** [comment]
Hi Albert,
Many thanks for picking up this ticket from a few years ago! I've tried the
GPCRdb Knime nodes, and got the accessible residues! I haven't used them in
a while :)
Hope you are doing well,
Best wishes,
Márton
